name: Android Unit Test

on:
  push:
    branches:
      - main
      - dev/*

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      # チェックアウト
      - uses: actions/checkout@v2

      # JDKのセットアップ
      - name: set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'

      # Gradleのキャッシュ復元
      - uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      # 実行権限付与
      - name: Make gradlew executable
        run: chmod +x ./gradlew

      # テスト
      - name: Test with Gradle
        run: ./gradlew test --stacktrace