name: Android Unit Test

on:
  push:
    branches:
      - main
      - dev/*

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      # チェックアウト
      - uses: actions/checkout@v3

      # JDKのセットアップ
      - name: set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'

      # Gradleのキャッシュ復元
      - uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      # google-services.jsonのコピー
      - name: copy google-service
        env:
          GOOGLE_SERVICE: ${{ secrets.GOOGLE_SERVICE_JSON }}
        run: echo $GOOGLE_SERVICE | base64 --decode --ignore-garbage > ./app/google-services.json

      # 実行権限付与
      - name: Make gradlew executable
        run: chmod +x ./gradlew

      # テスト
      - name: Test with Gradle
        run: ./gradlew test

      # JUnit Report Action
      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v3.8.0
        if: success() || failure() # always run even if the previous step fails
        with:
          report_paths: '**/build/test-results/*/TEST-*.xml'